### ISSUE TITLE
extension in the Utils.swift should be marked as public

### ISSUE THREAD

**Issue by tomisacat** [SoySauceLab/CollectionKit#36]
extensions and methods in `Utils.swift` should be marked as public so you don't have to repeat in demo project.

**Comment by lkzhao** [comment]
This is something that was considered. The reason why we are not doing it is because exporting these helper methods might cause conflict if you use libraries like [SwifterSwift](https://github.com/SwifterSwift/SwifterSwift). Feel free to grab the file and put it into your own projects. or include a helper library like SwifterSwift
