### ISSUE TITLE
Large Navbars 

### ISSUE THREAD

**Issue by Narsail** [SoySauceLab/CollectionKit#48]
Is the SizeProvider called for every data object in the Data Provider when the Collection View Size is changing? I have around 1300 items in my data and when using the Large Navigationbars the scrolling is seriously stuttering.

I checked what the source of the stuttering might be and I found that the sizeProvider of every cell is called every time when the size of the collectionView changes. That might be the culprit.

See the Example:
![21zmub](https://user-images.githubusercontent.com/7859096/34471979-be8f0758-ef56-11e7-8757-5859e1f0a86d.gif)

**Comment by lkzhao** [comment]
CollectionView always invalidate's its layout when its size changes. The reason being that some layouts are calculated from the collectionView's size. I understand that there are situations like this where one of the axis is not used and might change frequently. For `UICollectionView`, what they do is they ask the layout for [shouldInvalidateLayoutForBoundsChange](https://developer.apple.com/documentation/uikit/uicollectionviewlayout/1617781-shouldinvalidatelayoutforboundsc) to determine whether or not it should recalculate. We can implement something similar to that. But it would require some more thought since layout in CollectionKit can be composable.
As I can see from your layout, there is actually a better way to optimize. Since you have the same size for every cell, you actually don't need to do layout calculation for each cell. You can implement your own layout that doesn't use the sizeProvider at all.

Try the following layout:
```swift

public class FixedSizedLayout<Data>: CollectionLayout<Data> {

  var cellHeight: CGFloat = 84
  var spacing: CGFloat = 10
  var collectionWidth: CGFloat = 0
  var numberOfItems: Int = 0

  public override func layout(collectionSize: CGSize,
                              dataProvider: CollectionDataProvider<Data>,
                              sizeProvider: @escaping (Int, Data, CGSize) -> CGSize) {
    // store the following information necessary when calculating cell frame and contentSize
    numberOfItems = dataProvider.numberOfItems
    collectionWidth = collectionSize.width
  }

  public final override var contentSize: CGSize {
    return CGSize(width: collectionWidth,
                  height: CGFloat(numberOfItems) * (cellHeight + spacing) - spacing)
  }

  public final override func frame(at: Int) -> CGRect {
    return CGRect(x: 0, y: CGFloat(at) * (cellHeight + spacing),
                  width: collectionWidth, height: cellHeight)
  }

  public override func visibleIndexes(activeFrame: CGRect) -> [Int] {
    let minIndex = Int(activeFrame.minY / (cellHeight + spacing))
    let maxIndex = Int(activeFrame.maxY / (cellHeight + spacing))
    return Array(minIndex...maxIndex)
  }
}
```

Note that layout is very optimized. No matter how many cell you have it will always calculate in O(1) time.

**Comment by Narsail** [comment]
Okay, thanks for that suggestion. I will try it today :)

**Comment by lkzhao** [comment]
Hmm weird. Are you using any shared CollectionProvider, CollectionViewProvider, or layout by any chance?

**Comment by Narsail** [comment]
What do you mean with shared? They are all only used in one CollectionComposer and used by one CollectionView.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Narsail** [comment]
@lkzhao Do you need a sample project to look for yourself?

**Comment by lkzhao** [comment]
@Narsail  Yes that would be great.

**Comment by lkzhao** [comment]
Please reopen if you are still experiencing problem.

Also try updating to the latest v2.
