### ISSUE TITLE
Scrolling on tvOS

### ISSUE THREAD

**Issue by yonaskolb** [SoySauceLab/CollectionKit#55]
Hey, great library! 
I know tvOS isn't officially supported (I just made a PR to add it to Carthage and Cocoapods #54), but it would be nice to get it fully working.

At the moment if you make a view focusable, you can scroll through the collection. But if you scroll off screen, the scroll view jumps back to top of the scrollview. This is maybe because the focus engine tries to automatically scroll to the focused view which may be reused and now in a different place?

In addition to this it would be great to have a `focusHandler` similar to the `tapHandler`

**Comment by yonaskolb** [comment]
I just created a test `ViewProvider` that doesn't use the reuse manager and just creates a new view every update, but the scrolling issue is still present, so maybe it's not about reusing views

**Comment by lkzhao** [comment]
Okay, I see you point.

Spent a hour trying to get it working, but looks like it is not going anywhere. Seem like there are tight coupling between UICollectionView and the focusEngine in tvOS.

Sorry mate, since it requires some hack to get it work, and I dont write tvOS app. I have to drop tvOS support ATM until it becomes very usable.
