### ISSUE TITLE
Table shake when scroll to bottom

### ISSUE THREAD

**Issue by TMTBO** [SoySauceLab/CollectionKit#63]
scroll to bottom, and keep scroll with scrollview bounce, the table shake when finger scroll to the margin of two item view

**Comment by zhengzhou** [comment]
got the same, Especially when I use the Nib file.

**Comment by lkzhao** [comment]
Not seeing this myself, can you guys give me an example project?

**Comment by zhengzhou** [comment]
@lkzhao 
simple demo
https://github.com/zhengzhou/CollectionKitDemo

**Comment by daishuyi** [comment]
I think it is viewDidLayoutSubviews, you can make a break in the method. It is invoked when scroll to bottom, and collectionView frame will be reset. So you can set frame in viewSafeAreaInsetsDidChange, or auto layout.
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        collectionView.frame = view.bounds
    }

**Comment by zhengzhou** [comment]
@daishuyi 
that's did work. thank you very much.

**Comment by lkzhao** [comment]
@zhengzhou A temporary solution for you. Do a check before setting the frame should work.
```swift
      if collectionView.frame != view.bounds {
        collectionView.frame = view.bounds
      }
```

CollectionView removes or inserts a view when it goes on/offscreen. And with Auto layout, `viewDidLayoutSubviews` is triggered. Apparently `UIScrollView` has this bug where it resets the content offset to zero when `frame` is assigned.

This doesn't happen with the CollectionKit example project because it doesn't use auto layout and won't trigger `viewDidLayoutSubviews`.

I will see what I can do to overcome this issue in the next release.

**Comment by lkzhao** [comment]
Fixed in v1.3.1. Thanks for reporting. And sorry for the late fixes.

**Comment by tigati** [comment]
This fix breaks UIPageViewController default behaviour. Scrolling to last page becomes unpredictable.

**Comment by lkzhao** [comment]
@tigati Please see if @humblehacker's patch https://github.com/SoySauceLab/CollectionKit/pull/77 fix the issue for you. Checkout the latest master

```
pod "CollectionKit", :git => "https://github.com/SoySauceLab/CollectionKit.git"
```
