### ISSUE TITLE
Proposal: add WobbleAnimator to the framework

### ISSUE THREAD

**Issue by brightfuture** [SoySauceLab/CollectionKit#80]
Wobbling animation is extensively used in apps, at least more than the scale animation, although WobbleAnimator can be added by dragging code from the example, it makes sense to add this animator to the framework, since there are only 2 animators available as of yet.

**Comment by lkzhao** [comment]
Wobbling animation, requires another library as its dependency. which is why I don't have it included in the project. But we can probably create another pod that provides the WobbleAnimation.

This way, people who don't need wobble animation doesn't need to pull in more than one dependency.
And people who want this feature just need to add an extra line inside their podfile.

what do you guys think?

**Comment by brightfuture** [comment]
What's the problem with pulling in another dependency? YetAnotherAnimationLibrary is awesome anyway. 

People often come for a easy solution for complex things, one extra step scares a lot of people away.

**Comment by HiroshiHorie** [comment]
Doesn't look like a lot code so.... if someone could make WobbleAnimator dependency free would be great. I will try when I have time.

**Comment by lkzhao** [comment]
@brightfuture @HiroshiHorie WobbleAnimator is added as a subspec in v2.1.0.

Just use 
```ruby
pod "CollectionKit/WobbleAnimator"
```

to include it in your project.

But in the future we should try to get rid of the dependency if possible.
