### ISSUE TITLE
No Prefetch? Scroll performance issues

### ISSUE THREAD

**Issue by agotfredsen** [SoySauceLab/CollectionKit#86]
Hi . First great work with CollectionKit . I Love it but I have huge performance issues with it. And noticed some strange things. 

There are no prefetch and no preload of views(cells) . running simple print() debug I can see that the views are created just as they become visible . That can't be right . That creates huge performance issues when scrolling . I need to be able to draw the view graphics before it enters the visibleframe.

Looking at for example Texture by Facebook https://github.com/texturegroup/texture .. they preload not only one but 2-3 cells/views/nodes before becoming visible in order to get 60 fps scroll

There are no control of how many view I would like to preload / prefetch

I really really like this kit but I can't use it because of this ... and I really would not like to rewrite all of my code ...

**Comment by lkzhao** [comment]
There is a method to control whether or not to preload the cell. It is currently controlled at the layout level.

You can use insetVisibleFrame(by insets: UIEdgeInsets) and specify a negative insets to achieve the preloading effect.

However this doesn’t necessarily improve scrolling performance. It does let you prefech data for those cells. But it still takes main thread time to decide and rasterize text. it is just that this will not happen when the cell become on screen, but at a different time. The way that texture improves performance is mostly due to background layout, rasterization and decoding. 

In the end, CollectionKit’s goal is not to have better performance than UICollectionView.

**Comment by lkzhao** [comment]
There is the possibility of combining Texture with CollectionKit. 

However nowadays devices are very capable of doing 60fps as long as you don’t decode images on Mainthread. I usually use PINRemoteImage with CollectionKit, and I have no performance problem.

As device becoming faster, there even less reason to optimize this part of the application.

**Comment by agotfredsen** [comment]
> You can use insetVisibleFrame(by insets: UIEdgeInsets) and specify a negative insets to achieve the preloading effect.

That did the trick . Now it works great :) Thanks
