### ISSUE TITLE
How to implement Infinity scroll ?

### ISSUE THREAD

**Issue by lohenyumnam** [SoySauceLab/CollectionKit#96]
Hello guys, this framework seems to be cool. I have a few questions.

1. In the CollectionKitExample there is an example "ArticleExample" can you guys tell me if its possible to add infinite scrolling? if yes how?
2. Is this framework production ready?

**Comment by lkzhao** [comment]
1. just implement `scrollViewDidScroll` and observe the contentOffset. if it reaches the end, update your provider's dataSource to include more data. 

Checkout the `Chat` example. It shows you how to do infinite scroll. The example is probably more complicated than what you need since it is loading more data at the top. if you are loading more data at the bottom it is easier.

2. It is production ready. I have used it in Bitmoji app. which is the most downloaded app last year.
